### ISSUE TITLE
Forbidden link

### ISSUE THREAD

**Issue by lattice0** [greensheep/plex-server-docker-rpi#13]
https://downloads.plex.tv/plex-media-server/0.9.16.6.1993-5089475/PlexMediaServer-0.9.16.6.1993-5089475-neon-armv7.spk:
2018-01-19 19:07:16 ERROR 403: Forbidden.

**Comment by greensheep** [comment]
I’ll be updating this soon to the latest Plex version. Should get time this weekend!

**Comment by lattice0** [comment]
Where did you get that link from? Can't find it in the plex website. Wanted to try it now.

**Comment by greensheep** [comment]
It’s very old, you can swap it for the latest version from the Plex website by editing the Dockerfile.

The prebuilt docker image with that version is still on the docker hub.
