### ISSUE TITLE
Unable to use network drive for plex/config volume

### ISSUE THREAD

**Issue by IMNotMax** [greensheep/plex-server-docker-rpi#16]
Hi, first, great work :)
But I have an issue, if I try to use a network drive to store the plex/config and /plex/data, but my plex media server does not start.
If I use a local directory (on the raspberry pi 3 sd card, like /home/pi/media/plex/config) it works like a charm.
I use to have sd card corruption issues on my previous plex installs. I would like to store the config and data on a bigger network drive.

FYI, I mount the drive on startup on /home/pi/media/PlexHDD, it's a FAT32 hdd drive, SMB1 (old apple timecapsule)

Below the error from the logs

> pi@raspberrypi3:~/media $ docker logs -f plex
> Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
> Crash Uploader options (all are required):
>   --directory arg       Directory to scan for crash reports
>   --serverUuid arg      UUID of the server that crashed
>   --userId arg          User that owns this product
>   --platform arg        Platform string
>   --platformVersion arg Platform version string
>   --vendor arg          Vendor string
>   --device arg          Device string
>   --model arg           Device model string
>   --sentryUrl arg       Sentry URL to upload to
>   --sentryKey arg       Sentry Key for the project
>   --version arg         Version of the product
> ^C
> 

And the docker command I use

> docker run -d --name plex --net host -p 32400:32400 --restart always --volume /home/pi/media/PlexHDD/plex/config:/config --volume /home/pi/media/PlexHDD/plex/data:/data --volume /home/pi/media/PlexHDD:/PlexHDD --volume /etc/localtime:/etc/localtime:ro greensheep/plex-server-docker-rpi:latest

any ideas ?

**Comment by greensheep** [comment]
Hi! Not sure what that could be, but a quick google suggests it may not be network drive related. I use a USB drive for my setup so it would be difficult for me to replicate.

Sorry I can't be of more help, let me know if you get it fixed!

**Comment by IMNotMax** [comment]
Ok I will try a USB drive. The network drive looks good. I can create modify files... I’ll keep you informed !

**Comment by IMNotMax** [comment]
USB Drive works, network drive don't (for me)
