### ISSUE TITLE
Can't access any files or Media, everything appears to be blank in Plex

### ISSUE THREAD

**Issue by BrodyStone21** [greensheep/plex-server-docker-rpi#18]
I followed the instructions as specified, and I got this issue. When attempting to add Media to Plex it can't see anything. If I go to /mnt it appears to be empty. I just tried the below command and now I can see "WD_Black" the name of my drive but it's empty. Any suggestions?

`sudo docker run -d --name plex --net host -p 32400:32400 --restart always --volume /mnt/usb/WD_Black/Media/Plex/config:/config --volume /mnt/usb/WD_Black/Media/Plex/data:/data --mount source=WD_Black,destination=/WD_Black greensheep/plex-server-docker-rpi:latest`

**Comment by greensheep** [comment]
Did you manage to resolve this? Could it be a permissions problem? I just pushed a new version that might help... try setting the `SET_PLEX_UID` and `SET_PLEX_GID` env vars to the owner of the files - see README for details. (btw, this is new and works for me but I've not tested it extensively!).

**Comment by BrodyStone21** [comment]
Tom,

Thanks for the reply, sorry I didn't reply back sooner. It was a
permissions problem that I resolved by giving the "plex" user on my machine
proper permissions. I have since migrated to an Nvidia Shield TV for Plex.
Thank you for your assistance.

Brody

**Comment by greensheep** [comment]
No worries, thanks for the update and glad you found a solution 🙂
