### ISSUE TITLE
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign

### ISSUE THREAD

**Issue by SoylentGraham** [greensheep/plex-server-docker-rpi#19]
Running on a pi 3b+.
This is a clean raspbian (a few months old, but nothing altered, other than enabling ssh)

Just ran the instructions directly from readme (with `sudo`)

Not sure where this command line `--serverUuid` comes from
```
pi@raspberrypi:~ $ sudo  docker run --name plex --net host -p 32400:32400 --restart always --volume $(echo $HOME)/media/plex/config:/config --volume $(echo $HOME)/media/plex/data:/data greensheep/plex-server-docker-rpi:latest
Unable to find image 'greensheep/plex-server-docker-rpi:latest' locally
latest: Pulling from greensheep/plex-server-docker-rpi
ebe5f2b76040: Pull complete 
1a1e10ff4b41: Pull complete 
2b88cf08649f: Pull complete 
Digest: sha256:fa6dfc8e9ae7f66d3fecf5715fd9cc55f1720685bb25d2db1664e057526c6bc2
Status: Downloaded newer image for greensheep/plex-server-docker-rpi:latest
WARNING: Published ports are discarded when using host network mode
Error in command line:the argument for option '--serverUuid' should follow immediately after the equal sign
Crash Uploader options (all are required):
```

**Comment by greensheep** [comment]
Not seen this before, but I just pushed a new version that changed a quite a few things so you could try that

**Comment by SoylentGraham** [comment]
Oh, I forgot to comment on this. This error came up with other plex docker images too, so I guess it was something related to my raspbian image, or docker, or both and probably not related to your one.

I've just moved and finally got an internet connection, so I will start from fresh isos and try again. I'll reopen if it comes up again.
