### ISSUE TITLE
Plex Server Error

### ISSUE THREAD

**Issue by ivoribeiro** [greensheep/plex-server-docker-rpi#5]
HypriotOS: root@black-pearl in ~/plex-server-docker-rpi/plex on master*
$ docker logs plex
start.sh: line 12:    10 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:    10 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:    10 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:     8 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:     8 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:    11 Illegal instruction     (core dumped) ./Plex\ Media\ Server
start.sh: line 12:    10 Illegal instruction     (core dumped) ./Plex\ Media\ Server

**Comment by greensheep** [comment]
I can't reproduce this, could you share some more details about your setup (pi / hypriot version)?

I've only ever seen this error once when I accidentally used the wrong Plex binary during testing. Are you using something other than a Raspberry Pi 2?

**Comment by ivoribeiro** [comment]
I'm using a Pi 1

A qui, 3/03/2016, 22:30, Tom Hill notifications@github.com escreveu:

**Comment by greensheep** [comment]
That's it then. The Pi2 has an ARMv7 cpu while the Pi1 is v6.

I have a Pi1 so will so will attempt a build over the weekend using a
different Plex binary.

On Thursday, 3 March 2016, Ivo RIbeiro notifications@github.com wrote:

> I'm using a Pi 1
> 
> A qui, 3/03/2016, 22:30, Tom Hill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> escreveu:
> 
> > I can't reproduce this, could you share some more details about your
> > setup
> > (pi / hypriot version)?
> > 
> > I've only ever seen this error once when I accidentally used the wrong
> > Plex binary during testing. Are you using something other than a
> > Raspberry
> > Pi 2?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/greensheep/plex-server-docker-rpi/issues/5#issuecomment-191995550
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/greensheep/plex-server-docker-rpi/issues/5#issuecomment-191997805
> .

## 

Green Sheep Media Ltd.
www.greensheep.co.uk // tom@greensheep.co.uk // 0114 360 2777
Escape The Flock..

**Comment by greensheep** [comment]
Did some checking and there isn't an ARMv6 version of Plex so you're out of luck I'm afraid :(

If you have access to a Pi 2, try that because it works brilliantly!
